### ISSUE TITLE
Support for azure blob storage?

### ISSUE THREAD

**Issue by a3rosol** [jmaitrehenry/docker-azurefile-plugin#6]
Hi Julien,

do you plan on supporting azure blob storage as well? I'm pretty new to the docker world and am looking for an easy way to mount blob containers without modifying the docker container and am overwhelmed by this. There seems to be support for s3 but none (afaik) for azure without fiddling around with minio :(

Any help would be appreciated

**Comment by jmaitrehenry** [comment]
Hi @a3rosol, this plugin is really only for Azure file, but Minio is a great project and you could give it a try if you want.

**Comment by a3rosol** [comment]
Wow, this was fast! Thanks! I'm using minio already but was looking for a "clean" solution where the volume comes with an abstraction layer like your plugin. Do you know if there are other plugins that can deal with azure blobs? or do I have to install rexray and minio?

**Comment by jmaitrehenry** [comment]
I'm not aware of any plugin/solution other than RexRay and Minio, I'm sorry.
But RexRay and Azure storage could be a solution without using S3 but unmanaged disk. It's something I already experimented with ([Blog post](https://jmaitrehenry.ca/2018/01/10/using-rex-ray-with-docker-swarm-on-azure/)), but using unmanaged disk was not something I like and I finally change for Portworx in production.

**Comment by a3rosol** [comment]
Thank you, I will start experimenting with rexray and minio then :)
