### ISSUE TITLE
Incorrect Azure Volume Name

### ISSUE THREAD

**Issue by Edward-MS** [jmaitrehenry/docker-azurefile-plugin#8]
When I run 
$ docker volume create --name **my_volume** -d jmaitrehenry/azurefile
It shows this error msg.
Error response from daemon: create az_volume: VolumeDriver.Create: error creating azure file share: storage: service returned error: StatusCode=400, ErrorCode=**InvalidResourceName**, ErrorMessage=The specifed resource name contains invalid characters.

I think volume name can't contain underscore.

**Comment by jmaitrehenry** [comment]
You right, it's an invalid name, the doc need to be fixed.
Thanks for letting us know!
